### ISSUE TITLE
Unable to build with Node 7.x stable (works with 6.x LTS)

### ISSUE THREAD

**Issue by mtho11** [ManageIQ/ui-components#44]
Node 6.x is LTS is good, but 7.x stable doesn't run (at least on OS/X). Since it is the stable version and we are in Dev, it should probably also run in 7.x.

Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in Missing binding ui-components/node_modules/node-sass/vendor/darwin-x64-51/binding.node
    Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 7.x

    Found bindings for the following environments:
      - OS X 64-bit with Node.js 6.x

    This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass` to build the binding for your current environment.

**Comment by karelhala** [comment]
Try running `npm rebuild node-sass`, it should resolve this problem.

**Comment by mtho11** [comment]
@karelhala that doesn't seem to resolve the issue, maybe its just me or platform differences?

**Comment by himdel** [comment]
@mtho11 is this still a problem? I'd try simply removing `node_modules` and doing a fresh `npm install` (well, or `yarn` :)).

**Comment by mtho11** [comment]
@himdel yes, but I'm sure its platform specific - OS/X.

**Comment by himdel** [comment]
@mtho11 Can we close this?

I assume node 8 is usable again on macs?

**Comment by mtho11** [comment]
Yes, closing.
